/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_projects.strategy_pattern.good_design.strategy_pattern_challenge_example;

import java_projects.strategy_pattern.good_design.strategy_pattern_challenge_example.camera_app.BasicCameraApp;
import java_projects.strategy_pattern.good_design.strategy_pattern_challenge_example.camera_app.CameraPlusApp;
import java_projects.strategy_pattern.good_design.strategy_pattern_challenge_example.camera_app.PhoneCameraApp;

public class App {

    public static void main(String[] args) {
      PhoneCameraApp basicCameraApp = new BasicCameraApp();
      PhoneCameraApp cameraPlusApp = new CameraPlusApp();
      System.out.println("basicCameraApp Examples");
      basicCameraApp.take();
      basicCameraApp.save();
      basicCameraApp.edit();
      basicCameraApp.share();
      System.out.println("cameraAppPlus Examples");
      cameraPlusApp.take();
      cameraPlusApp.save();
      cameraPlusApp.edit();
      cameraPlusApp.share();
    }
}
