/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_projects.strategy_pattern.bad_design;

public class App {

    public static void main(String[] args) {
      Duck mallardDuck = new MallardDuck();
      Duck decoyDuck = new DecoyDuck();
      System.out.println(mallardDuck.quack());
      System.out.println(decoyDuck.quack());
    }
}
