/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_projects;

import org.junit.jupiter.api.Test;

import java_projects.strategy_pattern.bad_design.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
