/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_projects.strategy_pattern.good_design.decorator_pattern_challenge_example;

public class App {

    public static void main(String[] args) {
      Pizza pizza = new Cheese(new Pepporoni(new ThinCrustPizza()));
      System.out.println(String.format("The pizza is: %s", pizza.getDescription()));
      System.out.println(String.format("The total cost is: %s", pizza.cost()));
    }
}
